PKG_NAME=nanopb
PKG_URL=https://github.com/nanopb/nanopb
# 0.4.8
PKG_VERSION=nanopb-0.4.9.1
PKG_LICENSE=MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base
